# DCF Model Settings
dcf:
  discount_rate: 0.1
  terminal_growth_rate: 0.02

# Monte Carlo Simulation Settings
monte_carlo:
  iterations: 1000
  volatility: 0.2

# Sensitivity Analysis Settings
sensitivity:
  factors: [-0.1, 0, 0.1]

# File Paths
paths:
  data: "./data/"
  output: "./output/"
